/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package dads;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import mail.SendMail;

/**
 *
 * @author Nitin.A
 */
public class forgetPassword extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    int xMouse,yMouse;
    String username=null;
    Main m;
    /** Creates new form Profile */
    
    public forgetPassword(Main m,Connection conn) {
        initComponents();
        this.conn = conn;
        this.m = m;
        panel3.setVisible(false);
        this.setSize(371,160);
        btn2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        respondMsg = new javax.swing.JLabel();
        field1 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        btn = new javax.swing.JLabel();
        field3 = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        field7 = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        field8 = new javax.swing.JTextField();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        panel2.setBackground(new java.awt.Color(255, 51, 51));
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });

        respondMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        respondMsg.setForeground(new java.awt.Color(255, 255, 255));
        respondMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respondMsg.setText("Enter you Mail id.");

        field1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        field1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field1.setBorder(null);

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Email:");

        btn1.setBackground(new java.awt.Color(255, 51, 51));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn1.setForeground(new java.awt.Color(51, 51, 51));
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn1.setText("OK");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn1.setOpaque(true);
        btn1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn1MouseMoved(evt);
            }
        });
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 51, 51));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn2.setForeground(new java.awt.Color(51, 51, 51));
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn2.setText("Resend");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn2.setOpaque(true);
        btn2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn2MouseMoved(evt);
            }
        });
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
        });

        close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(respondMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(respondMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        panel3.setBackground(new java.awt.Color(51, 51, 51));

        btn.setBackground(new java.awt.Color(51, 51, 51));
        btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 51, 51));
        btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn.setText("OK");
        btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btn.setOpaque(true);
        btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMouseMoved(evt);
            }
        });
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });

        field3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        field3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field3.setBorder(null);

        label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("Confirm:");

        field7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        field7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field7.setBorder(null);

        label7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label7.setText("New-Password:");

        label8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label8.setText("Username:");

        field8.setEditable(false);
        field8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        field8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field8.setBorder(null);

        errorMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(field7, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(field3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(field8, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(field8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(field7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(1163, 655, 371, 431);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        btn.setBackground(new Color(51,51,51));
        btn.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_btnMouseExited

    private void btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMoved
        btn.setBackground(new Color(255,51,51));
        btn.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_btnMouseMoved

    private void btn1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseMoved
        btn1.setBackground(new Color(51,51,51));
        btn1.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_btn1MouseMoved

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        btn1.setBackground(new Color(255,51,51));
        btn1.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_btn1MouseExited

    private void btn2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseMoved
        btn2.setBackground(new Color(51,51,51));
        btn2.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_btn2MouseMoved

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new Color(255,51,51));
        btn2.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_btn2MouseExited

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        try{

            Random rand = new Random();
            int pin = rand.nextInt(10000);
            String formatted = String.format("%05d", pin);

            ps = conn.prepareStatement("update otp set code =\""+formatted+"\" where username=\""+username+"\"");
            ps.executeUpdate();

            respondMsg.setText("New otp is sent to your mail.");
            
            ps = conn.prepareStatement("select email from users where username=\""+username+"\"");
            rs = ps.executeQuery();
            rs.next();
            
            new Thread(new Runnable(){
                @Override
                public void run() {
                    try {
                        SendMail s = new SendMail(rs.getString("email"),"Message from DADS Official App.",formatted);
                    } catch (Exception ex) {}
                }
            }).start();
                 
        } catch (Exception ex) {}       
    }//GEN-LAST:event_btn2MouseClicked

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        close.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_closeMouseMoved

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(Color.WHITE);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        m.set_enabled();
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel2MousePressed

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panel2MouseDragged

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        try {
            if(label1.getText().equals("Otp:")){
                ps = conn.prepareStatement("select * from otp where username =\""+username+"\" and code=\""+field1.getText()+"\"");
                rs = ps.executeQuery();
                if(rs.next()){
                    field1.setVisible(false);
                    btn1.setVisible(false);
                    btn2.setVisible(false);
                    label1.setVisible(false);
                    panel3.setVisible(true);
                    respondMsg.setText("Now Change Your Password");
                    respondMsg.setFont(new Font("Segoe UI",Font.PLAIN,20));
                    this.setLocation(1163, 475);
                    this.setSize(371, 340);
                    field8.setText(username);
                }
                else respondMsg.setText("wrong otp.");
            }
            else if(label1.getText().equals("Email:"))
            {
                if(field1.getText().indexOf("@gmail.com")>5)
                {
                    ps = conn.prepareStatement("select * from users where email=\""+field1.getText()+"\"");
                    rs = ps.executeQuery();
                    if(rs.next()){
                        Random rand = new Random();
                        int pin = rand.nextInt(10000);
                        String formatted = String.format("%05d", pin);
                        new Thread(new Runnable(){
                            @Override
                            public void run() {
                                try {
                                    String email = field1.getText();
                                    SendMail s = new SendMail(email,"Message from DADS Official App.",formatted);
                                } catch (Exception ex) {}
                            }
                        }).start();
                            
                        username = rs.getString("username");
                        ps = conn.prepareStatement("select * from otp where username=\""+username+"\"");
                        rs = ps.executeQuery();

                        if(rs.next()){
                            ps = conn.prepareStatement("update otp set code =\""+formatted+"\" where username=\""+username+"\"");
                            ps.executeUpdate();
                        }
                        else
                        {
                            ps = conn.prepareStatement("insert into otp (username,code) values (\""+username+"\",\""+formatted+"\")");
                            ps.executeUpdate();
                        }
                        
                        label1.setText("Otp:");
                        respondMsg.setText("Otp is sent to your mail.");
                        btn2.setVisible(true);
                        field1.setText("");
                    }
                    else respondMsg.setText("Unregistered Email Id.");
                }
                else respondMsg.setText("Invalid email.");
            }
        } catch (SQLException ex) {}
    }//GEN-LAST:event_btn1MouseClicked

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        String newpass = field7.getText();
        String confirmpass = field3.getText();
        
        if(newpass.isEmpty()||confirmpass.isEmpty())
            errorMsg.setText("Field Empty");
        else
        {
            try 
            {
                if(newpass.equals(confirmpass))
                {
                ps = conn.prepareStatement("update users set password=? where username=?");
                ps.setString(1, confirmpass);
                ps.setString(2, username);
                ps.executeUpdate();
                m.set_enabled();
                m.change_respond();
                this.dispose();
                }
                else errorMsg.setText("password does'nt match");
            } catch (SQLException ex) {}     
        } 
    }//GEN-LAST:event_btnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn;
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel close;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field3;
    private javax.swing.JTextField field7;
    private javax.swing.JTextField field8;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JLabel respondMsg;
    // End of variables declaration//GEN-END:variables

}
