/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dads;

import java.awt.Color;
import java.util.HashMap;
import dads.HomePage;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;
import mail.SendMail;

/**
 *
 * @author Nitin.A
 */
public class Main extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement stmt=null;
    ResultSet rs=null;
    /**
     * Creates new form Main
     */
    void connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dads", "root", "anbu4444");
        }
        catch(Exception e){}
    }
    
    void login_setup(){
        firstPanel.setVisible(false);
        lastPanel.setVisible(false);
        phonePanel.setVisible(false);
        emailPanel.setVisible(false);
        btnLabel.setText("Sign In");
    }
    
    void register_setup(){
        firstPanel.setVisible(true);
        lastPanel.setVisible(true);
        phonePanel.setVisible(true);
        emailPanel.setVisible(true);
        btnLabel.setText("Sign Up");
    }
    
    void clearAll(){
        firstText.setText("First");
        lastText.setText("Last");
        phoneText.setText("Phone No");
        emailText.setText("Email Id");
        userText.setText("Username");
        passText.setText("Password");
        errorMsg.setText("");
    }
    
    String captalize(String name){
        String cap="";
        String words[] = name.split(" ");
        for(String word:words){
            name = word.substring(0,1).toUpperCase()+word.substring(1);
            cap += name+" ";
        }
        return cap.substring(0,cap.length()-1);
    }
    
    void set_enabled(){
        this.setEnabled(true);
    }
    
    void change_respond(){
        errorMsg.setText("Password changed successfully");
    }
    
    public Main() {
        initComponents();
        login_setup();
        connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPanel = new javax.swing.JPanel();
        btnLabel = new javax.swing.JLabel();
        firstPanel = new javax.swing.JPanel();
        firstText = new javax.swing.JTextField();
        passPanel = new javax.swing.JPanel();
        passText = new javax.swing.JPasswordField();
        cancelPanel = new javax.swing.JPanel();
        cancelText = new javax.swing.JLabel();
        errorMsg = new javax.swing.JLabel();
        phonePanel = new javax.swing.JPanel();
        phoneText = new javax.swing.JTextField();
        userPanel = new javax.swing.JPanel();
        userText = new javax.swing.JTextField();
        lastPanel = new javax.swing.JPanel();
        lastText = new javax.swing.JTextField();
        tab = new javax.swing.JPanel();
        tab1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JLabel();
        emailPanel = new javax.swing.JPanel();
        emailText = new javax.swing.JTextField();
        forget = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Doctor At Door Step");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 150)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        btnLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLabel.setForeground(new java.awt.Color(255, 51, 51));
        btnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLabel.setText("Sign In");
        btnLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLabelMouseMoved(evt);
            }
        });
        btnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        firstPanel.setBackground(new java.awt.Color(255, 232, 232));

        firstText.setBackground(new java.awt.Color(255, 232, 232));
        firstText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstText.setForeground(new java.awt.Color(102, 102, 102));
        firstText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstText.setText("First");
        firstText.setBorder(null);
        firstText.setOpaque(false);
        firstText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstText, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                .addComponent(firstText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        passPanel.setBackground(new java.awt.Color(255, 232, 232));

        passText.setBackground(new java.awt.Color(255, 232, 232));
        passText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(102, 102, 102));
        passText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passText.setText("Password");
        passText.setBorder(null);
        passText.setOpaque(false);
        passText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout passPanelLayout = new javax.swing.GroupLayout(passPanel);
        passPanel.setLayout(passPanelLayout);
        passPanelLayout.setHorizontalGroup(
            passPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passPanelLayout.setVerticalGroup(
            passPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passText, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        cancelPanel.setBackground(new java.awt.Color(255, 255, 255));
        cancelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        cancelText.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cancelText.setForeground(new java.awt.Color(255, 51, 51));
        cancelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelText.setText("Cancel");
        cancelText.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cancelTextMouseMoved(evt);
            }
        });
        cancelText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelTextMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cancelPanelLayout = new javax.swing.GroupLayout(cancelPanel);
        cancelPanel.setLayout(cancelPanelLayout);
        cancelPanelLayout.setHorizontalGroup(
            cancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelText, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        cancelPanelLayout.setVerticalGroup(
            cancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        errorMsg.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 51, 51));

        phonePanel.setBackground(new java.awt.Color(255, 232, 232));

        phoneText.setBackground(new java.awt.Color(255, 232, 232));
        phoneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneText.setForeground(new java.awt.Color(102, 102, 102));
        phoneText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phoneText.setText("Phone No");
        phoneText.setBorder(null);
        phoneText.setOpaque(false);
        phoneText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout phonePanelLayout = new javax.swing.GroupLayout(phonePanel);
        phonePanel.setLayout(phonePanelLayout);
        phonePanelLayout.setHorizontalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phonePanelLayout.setVerticalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phonePanelLayout.createSequentialGroup()
                .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        userPanel.setBackground(new java.awt.Color(255, 232, 232));

        userText.setBackground(new java.awt.Color(255, 232, 232));
        userText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userText.setForeground(new java.awt.Color(102, 102, 102));
        userText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userText.setText("Username");
        userText.setBorder(null);
        userText.setOpaque(false);
        userText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lastPanel.setBackground(new java.awt.Color(255, 232, 232));

        lastText.setBackground(new java.awt.Color(255, 232, 232));
        lastText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastText.setForeground(new java.awt.Color(102, 102, 102));
        lastText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastText.setText("Last");
        lastText.setBorder(null);
        lastText.setOpaque(false);
        lastText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout lastPanelLayout = new javax.swing.GroupLayout(lastPanel);
        lastPanel.setLayout(lastPanelLayout);
        lastPanelLayout.setHorizontalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastText)
                .addContainerGap())
        );
        lastPanelLayout.setVerticalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastPanelLayout.createSequentialGroup()
                .addComponent(lastText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(255, 51, 51));
        tab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tab1.setForeground(new java.awt.Color(255, 204, 204));
        tab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab1.setText("Sign In");
        tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        tab1.setOpaque(true);
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        tab.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 37));

        tab2.setBackground(new java.awt.Color(255, 255, 255));
        tab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tab2.setForeground(new java.awt.Color(255, 51, 51));
        tab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab2.setText("Sign Up");
        tab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        tab2.setOpaque(true);
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });
        tab.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, 37));

        emailPanel.setBackground(new java.awt.Color(255, 232, 232));

        emailText.setBackground(new java.awt.Color(255, 232, 232));
        emailText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(102, 102, 102));
        emailText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailText.setText("Email Id");
        emailText.setBorder(null);
        emailText.setOpaque(false);
        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailPanelLayout.createSequentialGroup()
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        forget.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        forget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forget.setText("Forget Password?");
        forget.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgetMouseMoved(evt);
            }
        });
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(forget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phonePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(firstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forget, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabelMouseMoved
        btnPanel.setBackground(new Color(255,51,51));
        btnLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLabelMouseMoved

    private void cancelTextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTextMouseMoved
        cancelPanel.setBackground(new Color(255,51,51));
        cancelText.setForeground(Color.WHITE);     
    }//GEN-LAST:event_cancelTextMouseMoved

    private void btnLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabelMouseExited
        btnPanel.setBackground(Color.WHITE);
        btnLabel.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_btnLabelMouseExited

    private void cancelTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTextMouseExited
        cancelPanel.setBackground(Color.WHITE);
        cancelText.setForeground(new Color(255,51,51));   
    }//GEN-LAST:event_cancelTextMouseExited
    
    private void btnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLabelMouseClicked

        if(btnLabel.getText().equals("Sign In")){
            String username = userText.getText();
            String password = String.valueOf(passText.getText());
            if(username.equals("")||passText.getText().equals("")||username.equals("Username")||passText.getText().equals("Password"))
                errorMsg.setText("Fill both the fields");
            else{
                try{
                    if (conn != null) {
                        String sql="select password from users where username=?";

                        stmt=conn.prepareStatement(sql);
                        stmt.setString(1,username);
                        rs = stmt.executeQuery();              

                        if(rs.next()){
                            if(rs.getString("password").equals(password))
                            {
                                new HomePage(conn,username).setVisible(true);

                                this.dispose();
                            }else errorMsg.setText("wrong password");
                        }else errorMsg.setText("wrong username");
                    }    
                }
                catch(Exception e){}
            }
        }
        else{
            if(userText.getText().equals("")||passText.getText().equals("")||lastText.getText().equals("")||phoneText.getText().equals("")||firstText.getText().equals("")||emailText.getText().equals("")
            ||userText.getText().equals("Username")||passText.getText().equals("Password")||lastText.getText().equals("Last")||phoneText.getText().equals("Phone No")||firstText.getText().equals("First")||emailText.getText().equals("Email Id"))
                errorMsg.setText("All fields must be filled.");
            else{
                String username = userText.getText();
                String password = String.valueOf(passText.getText());
                String first = firstText.getText();
                String last = lastText.getText();
                String phone = phoneText.getText();
                String email = emailText.getText();
                try{
                    if (conn != null) {
                        stmt=conn.prepareStatement("select * from users where name=?");
                        stmt.setString(1,captalize(first+" "+last));
                        rs = stmt.executeQuery();  
                        if(rs.next())
                        {
                            errorMsg.setText("Try giving another name.");
                        }
                        else
                        {
                            stmt=conn.prepareStatement("select * from users where username=?");
                            stmt.setString(1,username);
                            rs = stmt.executeQuery();              

                            if(rs.next()){
                                errorMsg.setText("account already exist");
                            }
                            else 
                            {
                                if(phone.length()==10)
                                {
                                    if(email.indexOf("@gmail.com")>5){
                                        stmt=conn.prepareStatement("select * from users where email=?");
                                        stmt.setString(1,email);
                                        rs = stmt.executeQuery();  
                                        if(rs.next())
                                        {
                                            errorMsg.setText("This email is already in use.");
                                        }
                                        else
                                        {
                                            stmt=conn.prepareStatement("insert into users(username,password,name,phone_no,email) values (?,?,?,?,?)");
                                            stmt.setString(1,username);
                                            stmt.setString(2,password);
                                            stmt.setString(3,captalize(first+" "+last));
                                            stmt.setString(4,phone);
                                            stmt.setString(5,email);
                                            stmt.executeUpdate();
                                            HomePage hp = new HomePage(conn,username);
                                            hp.setVisible(true);
                                            this.dispose();
                                        }
                                    }
                                }
                                else
                                {
                                    errorMsg.setText("Invalid Phone No");
                                }
                            }
                        }
                    }
                }
                catch(Exception e){}
            }
        }        
    }//GEN-LAST:event_btnLabelMouseClicked

    private void cancelTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTextMouseClicked
        dispose();
    }//GEN-LAST:event_cancelTextMouseClicked

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        tab2.setBackground(Color.WHITE);
        tab2.setForeground(new Color(255,51,51));

        tab1.setBackground(new Color(255,51,51));
        tab1.setForeground(Color.WHITE);
        login_setup();
        clearAll();
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        tab1.setBackground(Color.WHITE);
        tab1.setForeground(new Color(255,51,51));

        tab2.setBackground(new Color(255,51,51));
        tab2.setForeground(Color.WHITE);
        register_setup();
        clearAll();
    }//GEN-LAST:event_tab2MouseClicked

    private void firstTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstTextFocusGained
        if(firstText.getText().equals("First"))
            firstText.setText("");
    }//GEN-LAST:event_firstTextFocusGained

    private void firstTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstTextFocusLost
        if(firstText.getText().equals(""))
            firstText.setText("First");
    }//GEN-LAST:event_firstTextFocusLost

    private void lastTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastTextFocusGained
        if(lastText.getText().equals("Last"))
            lastText.setText("");
    }//GEN-LAST:event_lastTextFocusGained

    private void lastTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastTextFocusLost
        if(lastText.getText().equals(""))
            lastText.setText("Last");
    }//GEN-LAST:event_lastTextFocusLost

    private void userTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFocusGained
        if(userText.getText().equals("Username"))
            userText.setText("");
    }//GEN-LAST:event_userTextFocusGained

    private void userTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFocusLost
        if(userText.getText().equals(""))
            userText.setText("Username");
    }//GEN-LAST:event_userTextFocusLost

    private void passTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFocusGained
        if(passText.getText().equals("Password"))
            passText.setText("");
    }//GEN-LAST:event_passTextFocusGained

    private void passTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFocusLost
        if(passText.getText().equals(""))
            passText.setText("Password");
    }//GEN-LAST:event_passTextFocusLost

    private void phoneTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTextFocusGained
        if(phoneText.getText().equals("Phone No"))
            phoneText.setText("");
    }//GEN-LAST:event_phoneTextFocusGained

    private void phoneTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTextFocusLost
        if(phoneText.getText().equals(""))
            phoneText.setText("Phone No");
    }//GEN-LAST:event_phoneTextFocusLost

    private void emailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusGained
        if(emailText.getText().equals("Email Id"))
            emailText.setText("");
    }//GEN-LAST:event_emailTextFocusGained

    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        if(emailText.getText().equals(""))
            emailText.setText("Email Id");
    }//GEN-LAST:event_emailTextFocusLost

    private void forgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseExited
        forget.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_forgetMouseExited

    private void forgetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseMoved
        forget.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_forgetMouseMoved

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked
        forgetPassword fp = new forgetPassword(this,conn);
        fp.setVisible(true);   
        this.setEnabled(false);
    }//GEN-LAST:event_forgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLabel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel cancelPanel;
    private javax.swing.JLabel cancelText;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JTextField firstText;
    private javax.swing.JLabel forget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JTextField lastText;
    private javax.swing.JPanel passPanel;
    private javax.swing.JPasswordField passText;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JPanel tab;
    private javax.swing.JLabel tab1;
    private javax.swing.JLabel tab2;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
